# Generated by Django 5.0.2 on 2024-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='poster')),
                ('description', models.TextField(max_length=100)),
                ('release_date', models.IntegerField()),
                ('actors', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('trailer_link', models.URLField()),
            ],
        ),
    ]
