# Generated by Django 5.0.2 on 2024-03-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upcoming',
        ),
    ]
